Updated to fix compilation error
By separating the declaration of the sock_fprog structure from the
member initialization, I was able to successfully compile with gcc
version 4.6.3

Prior to this commit, I was getting the following error:

    linux.cc: In function ‘void Linux_NoNewPrivs_ForkTest()’:
    linux.cc:713:28: error: expected primary-expression before ‘.’ token
    linux.cc:714:28: error: expected primary-expression before ‘.’ token

With this commit, compilation if fine.